{% set version = "0.4.7" %}
{% set number = 0 %}

{% if cuda_compiler_version != "None" %}
{% set number = number + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  # only pull sources after upstream PyPI release...
  url: https://github.com/google/jax/archive/jaxlib-v{{ version }}.tar.gz
  sha256: 0578d5dd5035b5225cadb6a62ca5f93dd76b70292268502fc01a0fd9ca7001d0
  patches:
    - patches/0001-custom-build.diff
    - patches/0002-bazelrc-edit.diff  # [cudatoolkit == '11.8' or cudatoolkit == '11.2']
    - patches/0003-Patched-openxla-for-tf_runtime.patch     #[s390x]
    - patches/0001-Debug-log.patch

build:
  number: 2
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  script_env:
    - CUDA_HOME        #[build_type == "cuda"]
    - GCC_11_HOME      #[ppc_arch == "p10"]


requirements:
  build:
    - {{ compiler('c') }}                    # [ ppc_arch != "p10"]
    - {{ compiler('cxx') }}                  # [ ppc_arch != "p10"]
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - python {{ python }}                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy {{ numpy }}                                 # [build_platform != target_platform]
    - unzip
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel {{ bazel }}
    - bazel-toolchain
    # need protoc
    - libprotobuf {{ libprotobuf }}
    # needs protoc-gen-grpc
    - grpc-cpp {{ grpc_cpp }}
    # needs flatc
    - flatbuffers {{ flatbuffers }}
    # list libabseil here to ensure pinning correctly
    - libabseil {{ abseil_cpp }}
  host:
    - cudnn {{ cudnn }}      # [cuda_compiler_version != "None"]
    - nccl {{ nccl }}       # [cuda_compiler_version != "None"]
    - python {{ python }}
    - pip
    - numpy {{ numpy }}
    - libopenblas {{ openblas }}
    - wheel
    # list libabseil here to ensure pinning correctly
    - libabseil {{ abseil_cpp }}
    - flatbuffers <2.0.6
    - grpc-cpp {{ grpc_cpp }}
    - openssl
    - zlib {{ zlib }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy {{ scipy }}
    - re2
    - c-ares
    - libopenblas {{ openblas }}
    - nccl {{ nccl }}      #[build_type == 'cuda']
    - ml_dtypes >=0.0.3
      #- __cuda  # [cuda_compiler_version != "None"]
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
  commands:
    - pip check
    - python test_jaxlib.py
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
